config/routes.rb
SampleApp::Application.routes.draw do
  root :to => "home#index"
  match 'register' => 'users#new', :as => :register
  match "sign_in" => "sessions#new", :as => :sign_in
  match "sign_out" => "sessions#destroy", :as => :sign_out
  match "edit_profile" => "users#edit", :as => :edit_profile

  resources :users
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :stripe_token, :last_4_digits

  attr_accessor :password, :stripe_token
  before_save :encrypt_password
  before_save :update_stripe

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create

  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :last_4_digits

  def stripe_description
    "#{name}: #{email}"
  end

  def update_stripe
    if stripe_id.nil?
      if !stripe_token.present?
        raise "We're doing something wrong -- this isn't supposed to happen"
      end

      customer = Stripe::Customer.create(
        :email => email,
        :description => stripe_description,
        :card => stripe_token
      )
      self.last_4_digits = customer.active_card.last4
      response = customer.update_subscription({:plan => "premium"})
    else
      customer = Stripe::Customer.retrieve(stripe_id)

      if stripe_token.present?
        customer.card = stripe_token
      end

      # in case they've changed
      customer.email = email
      customer.description = stripe_description

      customer.save

      self.last_4_digits = customer.active_card.last4
    end

    self.stripe_id = customer.id
    self.stripe_token = nil
  end

  def self.authenticate(email, password)
    user = self.find_by_email(email)
    if user && BCrypt::Password.new(user.hashed_password) == password
      user
    else
      nil
    end
  end


  def encrypt_password
    if password.present?
      self.hashed_password = BCrypt::Password.create(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def require_user
    redirect_to root_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Welcome back"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:edit, :update]

  def new
    redirect_to root_path, :notice => "You are already registered" if current_user

    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Signed up!"
    else
      render :action => :new
    end
  rescue Stripe::CardError => e
    @user.errors.add :base, e.message
    @user.stripe_token = nil
    render :action => :new

  rescue Stripe::StripeError => e
    logger.error e.message
    @user.errors.add :base, "There was a problem with your credit card"
    @user.stripe_token = nil
    render :action => :new
  end

  def edit
  end

  def update
    current_user.update_attributes(params[:user])
    if current_user.save
      redirect_to root_path, :notice => "Profile updated"
    else
      render :action => :edit
    end
  rescue Stripe::StripeError => e
    logger.error e.message
    @user.errors.add :base, "There was a problem with your credit card"
    @user.stripe_token = nil
    render :action => :edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <p>Shouldn't you be coding?</p>
  <p><%= link_to "Edit Profile", edit_profile_path %>
<% else %>
  <p>Welcome to SampleApp, the social network for developers. Membership is a mere $20 a month.</p>
  <p><%= link_to "Join Today!", register_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>SampleApp</title>
    <%= stylesheet_link_tag :bootstrap, :sample_app %>
    <%= javascript_include_tag "https://js.stripe.com/v1/" %>
    <%= javascript_tag "Stripe.publishableKey = '#{STRIPE_PUBLISHABLE_KEY}';" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>

  </head>

  <body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><%= link_to "Sample App", root_path %></h3>
          <ul class="nav">
            <% if current_user %>
              <li>
                <%= link_to "Edit Profile", edit_profile_path %>
              </li>
              <li>
                <%= link_to "Sign Out", sign_out_path %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign In", sign_in_path %>
              </li>
              <li>
                <%= link_to "Register", register_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="main container">
      <div class="row">
        <div class="span6 columns">
          <% if flash.notice %>
            <div class="alert-message block-message success" id="notice">
              <%= flash.notice %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 columns">
    <fieldset>
      <%= form_for user, :html => {:class => 'form-stacked'} do |f| %>
        <% if user.errors.any? %>
          <div class="alert-message block-message error">
            <p><%= "#{pluralize(user.errors.count, "problem")} with your registration:" %></p>
            <div class="errors">
              <% user.errors.full_messages.each do |msg| %>
                <p><%= msg %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="clearfix">
          <%= f.label :name %>
          <div class="input">
            <%= f.text_field :name, :class => "field" %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :email %>
          <div class="input">
            <%= f.text_field :email, :class => "field" %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :password %>
          <div class="input">
            <%= f.password_field :password, :class => "field" %>
            <% if defined? editing %>
              <span class="help-block">Leave blank to keep your current password</span>
            <% end %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :password_confirmation %>
          <div class="input">
            <%= f.password_field :password_confirmation, :class => "field" %>
          </div>

          <%= f.hidden_field :stripe_token %>
          <%= f.hidden_field :last_4_digits %>
        </div>

        <% if user.last_4_digits %>
          <div id="change-card" class="clearfix">
            <label>Card</label>
            <div class="input">
              <span>
                Using card ending with 
                <%= user.last_4_digits %> 
                <%= link_to "(change)", "#" %>
              </span>
            </div>
          </div>
        <% end %>

        <noscript>
          <p>This form requires Javascript to use</p>
        </noscript>

        <div id="credit-card" style="<%= user.last_4_digits ? "display:none" : "display:block" %>">
          <div id="credit-card-errors" style="display:none">
            <div id="stripe-error-message" class="alert-message block-message error">
            </div>
          </div>

          <!-- these fields are disabled before submission and are never transmitted back to rails -->
          <div class="clearfix">
            <%= label_tag :credit_card_number %>
            <div class="input">
              <%= text_field_tag :credit_card_number, params[:credit_card_number], :class => "field", :disabled => true %>
            </div>
          </div>

          <div class="clearfix">
            <%= label_tag :cvv, "Security code (CVV)" %>
            <div class="input">
              <%= text_field_tag :cvv, params[:cvv], :class => "small", :disabled => true %>
            </div>
          </div>

          <div class="clearfix">
            <%= label_tag :expiry_date %>
            <div class="input">
              <%= date_select "", :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25, :disabled => true}, {:class => "small"} %>
            </div>
            <!-- empty -->
          </div>
          <span class="note">
            Your credit card details will be sent directly to our payment processor
          </span>
        </div>

        <div class="actions">
          <%= f.submit((defined?(editing) ? "Update" : "Register"), :class => "btn primary") %>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>

<%= render :partial => 'users/form', :locals => {:user => current_user, :editing => true} %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Register</h1>
</div>

<%= render :partial => 'users/form', :locals => {:user => @user} %>